[build]
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"
  CI = "false" 